#!/bin/bash

#---------------------------------------------
# kleiner Helfer zur Ermittlung, welche hosts
# eines gewuenschten Netzwerks erreichbar sind
# 23.09.2011, Ralf Mueller, OMC-Stuttgart
#---------------------------------------------

# Anzahl der Argumente ueberpruefen, Abbruch falls ungleich 2
# -----------------------------------------------------------

if [ $# != 2 ]
then
	printf "\v\tusage: ./nwping network-address subnet-mask
	 e.g.: ./nwping 10.6.49.96 255.255.255.224\n\n"
	exit 1
else

# Variablen aus den Argumenten uebernehmen und aufbereiten
# --------------------------------------------------------

net=`echo $1 | awk -F. {'print $1"."$2"."$3"."'}`
beg=`echo $1 | awk -F. {'print $4'}`
end=`echo $2 | awk -F. {'print $4'}`

# hosts pingen, ohne broadcast, je ein Paket, nur erfolgreiche anzeigen
# ---------------------------------------------------------------------
	printf "\n\tSkript laueft maximal `expr 254 - $end` Sekunden\n\n"
	for (( a=$beg+1 ; a<$beg+255-$end ; a++));
		do echo $a
		ping -c 1 $net$a | grep received
	done
	exit 0
fi
